create table product(
prod_ID INT Primary KEY,
prod_name varchar(50),
prod_desc varchar(100),
price numeric(6,2)
);

select * from product;

insert into product(prod_name,prod_desc,price)
values('laptop','this is laptop',5000),
('mobile','this is mobile',3000),
('monitor','this is monitor',4000);

ALTER TABLE product
ALTER COLUMN prod_id
ADD GENERATED BY DEFAULT AS IDENTITY;

insert into product(prod_name,prod_desc,price,prod_type)
values('chair','this is chair',1100,'furniture'),
('desk','this is table',2000,'furniture');

SELECT setval(
    pg_get_serial_sequence('product', 'prod_id'),
    (SELECT MAX(prod_id) FROM product)
);

alter table product
add prod_type varchar(10);

update product 
set prod_type = 'electronic'
where prod_id in (12,13,14);

update product
set price = price-(price*0.1)
where prod_type = 'electronic';

select prod_type,count(*)
from product
group by prod_type
having count(*)>1;

select prod_type,count(*)
from product
group by prod_type
order by count(*);

select prod_name,price
from product where price = (select max(price)
from product
where price<(select max(price) from product));

delete from product 
where price<(select avg(price) 
from product);

delete from product
where price in 
(select price 
from product 
where price <(
select avg(price) 
from product 
group by prod_type));


SELECT *
FROM product p
WHERE price < (
 SELECT AVG(price)
 FROM product
WHERE prod_type = p.prod_type
);

create table orders(
ord_id INT primary key,
ord_date date,
ord_typr varchar(15),
prod_id int,
FOREIGN KEY (prod_id)
    REFERENCES product(prod_id) 
	ON UPDATE CASCADE
ON DELETE CASCADE
);

drop table orders;



select * from product;


insert into orders(ord_id,ord_date,ord_typr,prod_id)
values(106,'2025-01-24','new',10),
(107,'2025-02-06','repeat',16),
(108,'2025-02-10','repeat',14),
(109,'2025-02-15','new',16),
(110,'2025-02-20','new',5);

select *
from product 
where prod_id = (select prod_id
				from orders
				group by prod_id
				order by count(*) desc
				limit 1);

select * from orders;

delete from product where prod_id = 10;

select avg(price) from product group by prod_type;