create index idx_prodname on product(prod_name);

select * from product;
select * from orders;
insert into product(prod_name,prod_desc,price,prod_type)
values ('bottle','this is bottle',200,'household');

--1. Fetch order details along with product name and price
select o.ord_id,o.ord_date,o.ord_typr,p.prod_name,p.price
from orders o inner join product p
on o.prod_id = p.prod_id;

--2. Total revenue generated by each product
select p.prod_id,p.prod_name,sum(p.price)
from orders o inner join product p
on o.prod_id = p.prod_id
group by p.prod_id;

--3. Products that have never been ordered
select p.prod_name, o.ord_id
from orders o right outer join product p
on o.prod_id = p.prod_id
where o.ord_id is null;

--4. Products with more repeat orders than new orders
select p.prod_name
from orders o1 inner

--5. Top 3 products based on number of orders
SELECT p.prod_id,p.prod_name, COUNT(o.ord_id) AS total_orders
FROM product p JOIN orders o 
ON p.prod_id = o.prod_id
GROUP BY p.prod_id
ORDER BY total_orders DESC
LIMIT 3;

--6. Total revenue from 'new' and 'repeat' orders separately
select o.ord_typr,sum(p.price) as total_revenue
from product p join orders o
on p.prod_id = o.prod_id
group by o.ord_typr;

--7. Month-wise total revenue
explain select TO_CHAR(o.ord_date,'MM') as months,sum(p.price) as revenue
from orders o inner join product p
on o.prod_id = p.prod_id
group by TO_CHAR(o.ord_date,'MM');

-- plsql
create or replace function add_numbers(a int,b int)
returns int
as $$
begin 
	return a+b;
	end;
$$ language plpgsql;

select add_numbers(9,9);

-- create a function that takes the product name as input and returns the price
create or replace function return_price(pprod_name varchar)
returns int
as $$
declare prod_price int;
begin
	SELECT price INTO prod_price from product where prod_name = pprod_name;
	return prod_price;
end;
$$ language plpgsql;

select return_price('car');
	
--return a table

create or replace function get_table()
returns table(id int,name varchar(20))--to specify how many values to return
as $$
begin
	return query select prod_id,prod_name from product; --name should be written 
end;													--matching from table
$$ language plpgsql;

select name from get_table();--to specfy what all to print from returned table

--write a procedure that takes product fields as input and add a new row in product table

create or replace procedure put_into_table(prd_name varchar(20),prd_desc varchar(100),pprice numeric(6,2),prod_typ varchar(30))
as $$
begin
insert into product (prod_name,prod_desc,price,prod_type)
values(prd_name,prd_desc,pprice,prod_typ);
end;
$$ language plpgsql;

call put_into_table('pen','this is pen',20,'stationary');

--write a procedure that takes prod id and discounted price ans input 
--and apply discounted price in all given prod id
create or replace procedure discounted_price(prd_id int,prd_price int)
as $$ 
begin
update product
set price = prd_price
where prod_id = prd_id;
end;
$$ language plpgsql;

call discounted_price(5,8000);
-- Create accounts table having id, name and balance field
CREATE TABLE accountsa (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20),
    balance_field NUMERIC(8,2)
);

-- Create account_audit table having account_id, old_balance, new_balance, changed_on fields
create table account_audit(
account_id int,
old_balance numeric(8,2),
new_balance numeric(8,2),
change_on timestamp default current_timestamp
);

ALTER TABLE accountsa
RENAME TO accounts;


--trigger function
create or replace function log_balance_update()
returns trigger
as $$
begin
insert into account_audit(account_id,old_balance,new_balance)
values(old.id, old.balance_field, new.balance_field);

return new;
end;
$$ language plpgsql;

------trigger------
create trigger balance_update_trigger
after update on accounts
for each row
when (old.balance_field is distinct from new.balance_field)
execute function log_balance_update();

select * from accounts;

insert into accounts(name,balance_field)
values('james',50000),
('paul',50000);
select * from account_audit;
insert into account_audit()


update accounts set balance_field=5000 where id =1


select * from account_audit